// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MVCommons","status":true,"description":"Great utility library that provides common-use and\nsimplified functions. Also expands default classes.","parameters":{}},
{"name":"OrangeCustomEvents","status":true,"description":"This plugin Will let you add or copy events to the current map","parameters":{}},
{"name":"Network","status":true,"description":"","parameters":{}}
];
