// Generated by CoffeeScript 1.9.1
(function() {
  var _Game_Interpreter_pluginCommand;

  _Game_Interpreter_pluginCommand = Game_Interpreter.prototype.pluginCommand;

  Game_Interpreter.prototype.pluginCommand = function(command, args) {
    if (command === 'Network') {
      switch (args[0]) {
        case "Connect":
          return $gameSystem.networkConnect();
      }
    }
  };

  Game_System.prototype.networkConnect = function() {
    var socket;
    console.log("network connect start");
    socket = io.connect('http://localhost:3030', {
      transports: ["websocket"]
    });
    socket.on('connect', function() {
      return console.log("connected!");
    });
    return console.log("network connect finish");
  };

}).call(this);
