// Generated by CoffeeScript 1.10.0

/*:
 * @plugindesc ツイートするやつ
 * @author kyubuns
 *
 * @help
 *
 * Plugin Command:
 *   Tweet (message)
 *
 * Example:
 *   Tweet \V[0001]点を取りました！ http://kyubuns.net/
 *
 * License:
 *   Copyright (c) 2015 kyubuns
 *
 *   This software is released under the MIT License.
 *   http://opensource.org/licenses/mit-license.php
 */

(function() {
  var _Game_Interpreter_command356;

  _Game_Interpreter_command356 = Game_Interpreter.prototype.command356;

  Game_Interpreter.prototype.command356 = function() {
    if (this._params[0].split(" ")[0] === 'Tweet') {
      $gameSystem.tweet(this._params[0]);
    }
    return _Game_Interpreter_command356.call(this);
  };

  Game_System.prototype.tweet = function(rawMessage) {
    var link, message;
    message = Window_Base.prototype.convertEscapeCharacters(rawMessage.slice(6));
    link = 'http://twitter.com/home?status=' + encodeURIComponent(message);
    window.open(link, '_blank');
    return console.log(message);
  };

  Game_System.prototype.tweetTest = function(rawMessage) {
    Graphics._renderer.render(SceneManager._scene);
    Graphics._renderer.view.toDataURL("image/png");
  };

}).call(this);
